
@eventId = {{ createEvent.response.body.id }}
###
@spotName = {{ createSpot.response.body.name }}

### listAll
GET http://localhost:3000/events

### listOne
GET http://localhost:3000/events/{{eventId}}

### update
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
    "name": "New Event",
    "description": "I'm a description",
    "date": "2017-01-01T00:00:00",
    "price": 200
}

### delete
DELETE http://localhost:3000/events/{{eventId}}
###

# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "New Event",
    "description": "I'm a description",
    "date": "2017-01-01T00:00:00",
    "price": 200
}
###

######################################################
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "A2"
}

### listAll
GET http://localhost:3000/events/{{eventId}}/spots

### Delete
DELETE http://localhost:3000/events/{{eventId}}

### reserve spot
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json

{
    "spots": ["{{spotName}}"],
    "ticket_kind": "full",
    "email": "teste@teste.com"
}